### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by lvtanxi** [Curzibn/Luban#1]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference

**Comment by Curzibn** [comment]
hi,

Cloud you show the complete code what you call to help find the bug, thanks!

**Comment by Curzibn** [comment]
你好，

能否放上你的完整调用代码，已经图片的具体信息？方便我定位问题。

**Comment by lvtanxi** [comment]
` @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (resultCode == RESULT_OK && requestCode == PhotoPicker.REQUEST_CODE && data != null) {
            List<String> photos = data.getStringArrayListExtra(PhotoPicker.KEY_SELECTED_PHOTOS);
            if (photos != null) {
                for (String photo : photos) {
                    File file = new File(photo);
                    double fileOrFilesSize = FileSizeUtil.getFileOrFilesSize(file, FileSizeUtil.SIZETYPE_KB);
                    Log.d("MainActivity", "fileOrFilesSize:" + fileOrFilesSize);
                    Luban.get(this)
                            .load(file)                     //传人要压缩的图片
                            .putGear(Luban.THIRD_GEAR)      //设定压缩档次，默认三挡
                            .setCompressListener(new OnCompressListener() { //设置回调
                                @Override
                                public void onSuccess(File newFile) {
                                    if (null != newFile) {
                                        loadImage(newFile);
                                        double fileOrFilesSize = FileSizeUtil.getFileOrFilesSize(newFile, FileSizeUtil.SIZETYPE_KB);
                                        Log.d("MainActivity", "fileOrFilesSize:" + fileOrFilesSize);
                                    }
                                }
                            }).launch();    //启动压缩
                }
            }

        }
    }`

**Comment by Curzibn** [comment]
选择的图片的尺寸，大小也放上来下
