### ISSUE TITLE
请教：微信对话界面，图片大小缩放算法

### ISSUE THREAD

**Issue by Speical** [Curzibn/Luban#10]
你好，请问你在完成此项目的过程中，研究过微信对话界面，图片显示到对话界面上的预览图的大小缩放规律吗？

**Comment by tanranran** [comment]
这个应该是更具Imageview 的大小生成的。

**Comment by Curzibn** [comment]
@Speical 这一块我暂时没时间具体的帮你解答
之前我做聊天的时候只是采用了简单的判断图片高宽与屏幕高宽之间的关系
      1、图片横向比较长的话设定 ImageView 宽最大为屏幕的1/2，高度根据比例设定
      2、图片竖向比较长的话设定 ImageView 高最大为屏幕的1/2，宽度根据比例设定
希望能对你有帮助

**Comment by Speical** [comment]
@Curzibn 感谢！！！
