### ISSUE TITLE
既然是公共库就不要弄那么多依赖

### ISSUE THREAD

**Issue by hello-earth** [Curzibn/Luban#100]
不想用rx都不行

**Comment by 3kqing** [comment]
是的，能不用RX吗，不想用啊

**Comment by champion32** [comment]
问题一:公共库是否可以依赖其他库
问题二:依赖了rx相关的两个库算不算多
问题三:题主的意思是luban依赖了其他库还是依赖了rx的库?如果是后者的话建议用一下rx试试手,不行的话clone一份代码,自己改下源码.demo测试使用
问题四:楼上的排斥rx是因为团队学习成本问题还是因为发现了rx的一些弊端?

**Comment by Zhangxxl** [comment]
方案一:作者开放了源代码,有需要自行修改
方案二:这个库不能满足你的需要, 自行寻找其他类似的库

**Comment by lsxiao** [comment]
如果项目中用了RxJava2，会有冲突，因为目前该库还没有升级支持RxJava2。
