### ISSUE TITLE
关于多图压缩的优化方案

### ISSUE THREAD

**Issue by Zhangxxl** [Curzibn/Luban#103]
>- 作者有没有把算法用**Jni**实现一遍的想法? 如果多线程压图的话,或者图片内容过大, 势必会导致OOM, 如果按照队列来处理, 又会导致压缩速度很慢, 或者能不能把图片数据处理交给jni,利用公共内存空间来避免OOM呢?  @Curzibn 
>- 具体可以参考 [Fresco](https://github.com/facebook/fresco)

**Comment by Curzibn** [comment]
感谢建议，这块需要时间，我会想办法实现的。 @Zhangxxl
