### ISSUE TITLE
压缩后返回的是原图片

### ISSUE THREAD

**Issue by liangfhNoDev** [Curzibn/Luban#105]
在success回调方法里面，打印出压缩后的文件的路径和大小与压缩前打印出来的是一模一样的，请问这是什么原因？图片是我保存在sd卡下面的图片文件。

**Comment by shaohui10086** [comment]
会有这种情况出现的，因为你要压缩的图片和最后的压缩要求符合，这时候会直接返回原图，因为不需要压缩
