### ISSUE TITLE
长图压缩出错

### ISSUE THREAD

**Issue by LongAgoLong** [Curzibn/Luban#11]
长图压缩有两个bug一个option会出现小于0

**Comment by LongAgoLong** [comment]
另一个压缩完返回为空

**Comment by LongAgoLong** [comment]
宽高为440*17907

**Comment by LongAgoLong** [comment]
我改了一下返回为byte[]不采取保存文件的方式再判断一下option适时跳出循环，可以处理长图了，但是着色不对呀，就像一张黑白图片，然后上面乱七八糟泼着色彩一样，大大有空看一下呗

**Comment by TangXiaoLv** [comment]
我也遇到相同bug
