### ISSUE TITLE
示例代码用不了呢。

### ISSUE THREAD

**Issue by andansky** [Curzibn/Luban#12]
Luban.get(this)
                    .load(file)                     //传人要压缩的图片
                    .putGear(Luban.THIRD_GEAR)      //设定压缩档次，默认三挡
                    .setCompressListener(new OnCompressListener() {
                        @Override
                        public void onStart() {
                        }

                        @Override
                        public void onSuccess(File file) {
                        }

                        @Override
                        public void onError(Throwable e) {

                        }
                    }).launch();    //启动压缩
我这里提示onStart跟onError不能用@Override啊

**Comment by andansky** [comment]
OnCompressListener里都没这两个方法。。。。。

**Comment by andansky** [comment]
已经提示压缩成功并能成功输出路径了，但是我顺着图片的保存路径找都没找到那个路径呢？

**Comment by Curzibn** [comment]
1、因为新 README 中的代码还未上传到 jcenter，所以导入久版本会有这个问题，目前已上传完成
2、图片的路径是安卓的缓存路径，你试试看 root 后用 re管理器 才能找到
