### ISSUE TITLE
文件名的问题

### ISSUE THREAD

**Issue by gaoshangqw** [Curzibn/Luban#13]
缓存的文件名直接是时间戳了。

**Comment by Curzibn** [comment]
你好
Luban 主要还是处理压缩以及返回文件，因为部分手机系统相册会把存储中的图片文件全部显示出来，这边处理的缓存文件是不加后缀的。
而且不同的项目在SD卡中建立的存储文件夹名称不一样，Luban 就不做专门的存储。
如果你需要对缓存文件做处理，可以在拿到文件后另行储存为jpg形式的文件。
