### ISSUE TITLE
小公告

### ISSUE THREAD

**Issue by Curzibn** [Curzibn/Luban#14]
1、我最近在找工作，Luban 也是这两天突然爆发起来，如果有问题请各位包涵
2、图片压缩是安卓开发的刚需，我希望能靠大家一起讨论完善 Luban
3、如果想把 Luban 用上线上产品的大大请直接用源码，并针对自家产品优化，不要因为 Luban 而对产品造成影响
4、我会不断花时间优化 Luban 项目，希望大家多多支持
5、想加入讨论的大家是希望建Q群，微信群，还是继续在 issues 中讨论，可以在本 issues 下发表意见

**Comment by justjavac** [comment]
用 Flarum 搭建个论坛吧。QQ群不适合讨论技术。

**Comment by gushoubang** [comment]
支持

**Comment by tanranran** [comment]
issues 吧，毕竟issues的作用就是这个。Q群，微信群 时间长了就会变质的

**Comment by justjavac** [comment]
@tanranran issues 的作用不是这个啊

**Comment by justjavac** [comment]
issues **!=** BBS

**Comment by tanranran** [comment]
@justjavac 参考这个，https://github.com/android-cn/android-discuss/issues
