### ISSUE TITLE
图片压缩后没有后缀名

### ISSUE THREAD

**Issue by CodeCatLYR** [Curzibn/Luban#160]
图片压缩后没有后缀名，上传服务器后，服务无法知悉文件类型格式

**Comment by Carey0732** [comment]
我也遇到这个问题了，没有后缀名，服务器无法解析

**Comment by imgod1** [comment]
怎么解决的啊 楼主

**Comment by lh1241698502** [comment]
我也遇到了这个问题，我把压缩后的文件重命名成“.png”的文件上传后服务端能识别图片了，mimeType是“image/png”，重命名之前的mimeType是null

**Comment by imgod1** [comment]
我是在压缩成功后 对文件重命名为压缩前的格式 rename一下就好

**Comment by lh1241698502** [comment]
@imgod1 怎么获取之前的格式能告诉我下吗，我也想采用你的这个方案

**Comment by imgod1** [comment]
从压缩前的文件的名称里面或者全路径里面 分割出原来的格式名哇...
/**
     * 返回文件的后缀名
     *
     * @param filePath 文件路径
     * @return 文件后缀名
     */
    public static String getFileType(String filePath) {
        if (!TextUtils.isEmpty(filePath)) {
            int endPosition = filePath.lastIndexOf(".");
            String type = filePath.substring(endPosition, filePath.length());
            return type;
        } else {
            return null;
        }
    }

**Comment by lh1241698502** [comment]
@imgod1 多谢

**Comment by pruas** [comment]
可以试试 https://github.com/pruas/Biscuit
