### ISSUE TITLE
为什么压缩之后的图片上传到服务器没有后缀呢

### ISSUE THREAD

**Issue by douya40** [Curzibn/Luban#165]
为什么压缩之后的图片上传到服务器没有后缀呢

**Comment by douya40** [comment]
/storage/emulated/0/Android/data/com.ssd.x_jwt/cache/luban_disk_cache/149820108454935  (生成之后没有图片后缀)

**Comment by douya40** [comment]
急呀！大神解答一下呀

**Comment by Curzibn** [comment]
你先在获取到的文件名后面加.jpg后缀，下个版本我会解决这个问题

**Comment by douya40** [comment]
我试过在后面加.jpg，加了之后图片就不显示了

**Comment by Curzibn** [comment]
你可能是png格式的，你在加后缀前先存下原文件的后缀格式吧。

**Comment by douya40** [comment]
也是.jpg格式的，只能你那边升级，不然我项目整块都要改压缩框架
，太难搞了

**Comment by douya40** [comment]
/storage/emulated/0/Android/data/com.ssd.x_jwt/cache/luban_disk_cache/149852562096417（1.1.2版本压缩之后取到的路径还是没有图片格式呀）

**Comment by Curzibn** [comment]
1.1.2 后的版本都有后缀
