### ISSUE TITLE
考虑用libjpeg压缩不是更好吗？

### ISSUE THREAD

**Issue by ChaserSheng** [Curzibn/Luban#168]
微信等其他的大厂app不是用的开启哈夫曼算法的libjpeg压缩的吗？单纯的bitmapfactory压缩倒是容易达到大小要求，但是质量难以保证。有试过本项目，基本能达到项目要求，但是清晰度还是不太满意的，特别是要求图片100k以下并且清晰的情况下

**Comment by githubzjh** [comment]
看要求了，要是100kb以下，libjpeg的优势就凸显出来了，要用就用libjpeg-turbo，压缩速度还快呢

**Comment by githubzjh** [comment]
您的项目有用到libjpeg了？我的qq767132387，要是有用到的话，可以交流一下
