### ISSUE TITLE
如何解决图片多次压缩清晰度变差的问题

### ISSUE THREAD

**Issue by HortonGou** [Curzibn/Luban#169]
我注意到将一张图片5.2M传到朋友圈微信压缩过后变为615k，再次上传615k的图片，微信不再进行压缩，此时再将图片传到微博，压缩到420k，将此图片再次传到微信仍旧是420k。说明反复压缩并不会图片变得恶劣。
而使用Luban压缩这张420k的图片时，直接压缩到81kb，此时图片已经无法查看了。
如何解决这个问题？

**Comment by jinbolx** [comment]
![default](https://user-images.githubusercontent.com/14304952/29060732-9e0a57ca-7c4d-11e7-9840-8b4a05237872.PNG)
把图片质量改成100试试，他的图像体积大幅度压缩依赖于这个图像质量的改变
