### ISSUE TITLE
computeSize计算不正确

### ISSUE THREAD

**Issue by beiyoujiayu** [Curzibn/Luban#171]
computeSize中计算srcwidth和srcheight中赋值语句有问题：
    srcWidth = srcWidth > srcHeight ? srcHeight : srcWidth;
    srcHeight = srcWidth > srcHeight ? srcWidth : srcHeight;
 srcWidth > srcHeight 时，srcheight并不会被重新赋值，因为srcwidth的值已被更改为srcheight。

**Comment by FangWW** [comment]
同问  这里如果是一张宽图  既宽大于长  计算出来的比例始终是1.0
