### ISSUE TITLE
RxJava+Luban同步调用实现多图压缩怎么实现？

### ISSUE THREAD

**Issue by Saxxhw** [Curzibn/Luban#172]
菜鸟一枚，求教。。。大神能在README.md中给个多图压缩调用示例吗？感谢

**Comment by Yanqilong** [comment]
@Saxxhw 我是这样做的，使用Luban同步压缩结合Rxjava2实现多图异步压缩

        /**
         * fileList是List<File>对象
         */
        Flowable.fromIterable(fileList)
                .map(new Function<File, File>() {
                    @Override
                    public File apply(File file) throws Exception {
                        return Luban.with(context).load(file).get();
                    }
                })
                .toList()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Consumer<List<File>>() {

                    @Override
                    public void accept(List<File> fileList) throws Exception {
                         //图片压缩完成得到list
                    }
                });
