### ISSUE TITLE
System.out: mkdir failed: EACCES (Permission denied) 

### ISSUE THREAD

**Issue by zhouhaoo** [Curzibn/Luban#173]
已经加入了读写权限了，手机运行版本为4.4。

日志：
07-07 17:50:43.073 25467-3546/com.tyd.logistic.app I/System.out: mkdir failed: EACCES (Permission denied) path = /storage/sdcard1/Android/data/com.tyd.logistic.app/cache
07-07 17:50:43.083 25467-3546/com.tyd.logistic.app W/ContextImpl: Failed to ensure directory: /storage/sdcard1/Android/data/com.tyd.logistic.app/cache: 400
07-07 17:50:43.083 25467-3546/com.tyd.logistic.app I/System.out: mkdir failed: EACCES (Permission denied) path = /storage/sdcard1/Android/data/com.tyd.logistic.app/cache
07-07 17:50:43.090 25467-3546/com.tyd.logistic.app W/ContextImpl: Failed to ensure directory: /storage/sdcard1/Android/data/com.tyd.logistic.app/cache: 400

**Comment by thduan** [comment]
这个问题的解决方法是什么？
