### ISSUE TITLE
循环遍历压缩多张图片会重复，有没有办法解决啊 大神？

### ISSUE THREAD

**Issue by dinghu** [Curzibn/Luban#179]
循环遍历压缩多张图片会重复，有没有办法解决啊 大神？

**Comment by Curzibn** [comment]
能否详细描述下问题，贴下你的代码已经压缩后图片的文件名截图

**Comment by hxkdidi** [comment]
这个刚遇到了

**Comment by hxkdidi** [comment]
因为你在同步处理才会重复，遍历方式不对，应该采用异步的方式进行递归

**Comment by dinghu** [comment]
我使用他的最新版本没出现这个问题了

**Comment by dinghu** [comment]
我使用他的最新版本没出现这个问题了

**Comment by hxkdidi** [comment]
我看了内存占用，遍历的方式会导致内存暴增，你可以看一下

**Comment by hxkdidi** [comment]
一张一张异步压缩的内存峰值只有遍历时候的一半

**Comment by dinghu** [comment]
内存我暂时没有关注呢，，，其实一般都是要同时压缩多张图片，单张压缩的应用场景不多！！！

**Comment by hxkdidi** [comment]
我的意思是传入多张然后一张一张处理

**Comment by Bobyang912** [comment]
@hxkdidi 是的，这种多图上传最容易占用大量内存，还是要关注一下内存才能判断自己写的代码是否比较合适！

**Comment by vihuela** [comment]
批量压缩没有问题啊

**Comment by hxkdidi** [comment]
@vihuela 只要是异步倒是没问题，我用的作者旧的

**Comment by huangShan-gitHub** [comment]
我也有这个问题，压缩list文件，会被遍历多次重复的数据出来，有解决的大佬没？使用 .setCompressListener(new OnMultiCompressListener() {}回调的话又报错，使用不了。
