### ISSUE TITLE
个人觉得应该增加onError接口

### ISSUE THREAD

**Issue by a1018875550** [Curzibn/Luban#2]
看了你写的代码，OnCompressListener的onSuccess方法是在try catch里的，既然这样说明可能会有失败，那么加个onError接口应该是极好的

**Comment by tanranran** [comment]
+1

**Comment by a1018875550** [comment]
而且压缩是个耗时的操作应该弄个线程管理吧？

**Comment by Curzibn** [comment]
谢谢 @a1018875550 的提醒，我会在下个版本加入onError结果。
至于线程的话我会添加RxJava版的调用方式，可以更方便管理线程。listener方式的调用则会说明由调用者自主控制线程

**Comment by a1018875550** [comment]
嗯嗯，我暂时做了个简单版rxLuban,其他博主的原版

**Comment by Curzibn** [comment]
想问下您在哪发现我的工具的？我自己的博客浏览数并无变化

**Comment by TangXiaoLv** [comment]
@Curzibn gank io 推荐了你的项目，所以你发现一天暴涨了近300start

**Comment by a1018875550** [comment]
恩，看到扔物线推荐了你，

**Comment by Curzibn** [comment]
天哪，居然是任物线大神，受宠若惊啊
