### ISSUE TITLE
压缩上传 图片损坏 

### ISSUE THREAD

**Issue by luocaca** [Curzibn/Luban#207]
楼主你好
压缩成功后，上传到服务器，偶尔会出现 图片 损坏的情况，
以下给出压缩只剩半张的图片

上传的图片机型：
小米4 
[
![error](https://user-images.githubusercontent.com/20178161/32413801-352c7240-c254-11e7-828b-f897ca9ea2b6.jpg)
](url)

**Comment by minj2me** [comment]
我也遇到过。。

**Comment by luocaca** [comment]
找了好久。说是国产rom 的压缩底层有问题。我还是没有一个很好的解决方案。

**Comment by luocaca** [comment]
so噶。已经解决问题。各家系统rom的问题。答案详询
http://www.jianshu.com/p/e5837a85e6cb
替换 压缩代码。
