### ISSUE TITLE
压缩gif后。glide无法播放了

### ISSUE THREAD

**Issue by ujffdi** [Curzibn/Luban#215]
如题，没压缩前可以播放

**Comment by lijingnan** [comment]
最近项目总加入gif，发现gif压缩后用fresco和glide都无法播放

**Comment by zwping** [comment]
luban不支持gif压缩，建议本地化修改代码避开gif图片压缩，[具体的看下这一楼的回复](https://github.com/Curzibn/Luban/issues/194)

**Comment by YZhongBin** [comment]
gif 压缩后变成了jpg

**Comment by zwping** [comment]
@YZhongBin 你可以用下luban的[迭代版](https://github.com/zwping/luban)
