### ISSUE TITLE
关于rxjava

### ISSUE THREAD

**Issue by tanranran** [Curzibn/Luban#22]
个人是不想用rxjava得，为了一个压缩引用rxjava和rxAndroid 会增大APK大大小，建议分离rxjava，出一个rxjava版本和普通版本。

**Comment by Curzibn** [comment]
好的，收到

**Comment by huijimuhe** [comment]
我鼓捣了一个用线程池的，ondestory可以cancel销毁线程,希望能帮得上。pull request#23
