### ISSUE TITLE
同步调用好像有问题，也可能是我使用姿势不对。。请知道的人能解答一下

### ISSUE THREAD

**Issue by ChenTianSaber** [Curzibn/Luban#224]
Luban.with(context).load(new File(path)).setTargetDir(FLASH_COMPRESS_PAHT).get().get(0).getAbsolutePath();

我是这样用的，报了java.lang.IndexOutOfBoundsException: Index: 0, Size: 0这个错误

**Comment by Curzibn** [comment]
你是调用了`load(new File(path))`也就是单图压缩，可以直接调用一下代码压缩：
```
Luban.with(context).setTargetDir(FLAS_COMPRESS_PATH).get(path).getAbsolutePath();
```
