### ISSUE TITLE
直接压缩bitmap

### ISSUE THREAD

**Issue by zouzhenglu** [Curzibn/Luban#232]
能不能支持直接压缩bitmap，现在我是保存到本地有了文件再压缩的

**Comment by MichaelJokAr** [comment]
这个为什么关闭了？是解决了还是不解决呀？

**Comment by IMAlex233** [comment]
我以为想问，为什么不能直接传bitmap对象

**Comment by zouzhenglu** [comment]
> 这个为什么关闭了？是解决了还是不解决呀？

我是一脸懵逼，，还是乖乖的保存本地先

**Comment by IMAlex233** [comment]
bitmap是位图，只要分辨率不改变大小就不会变，所以压缩了意义也没多大
