### ISSUE TITLE
你好，版本 1.1.3 不能用了吗？

### ISSUE THREAD

**Issue by lvfaqiang** [Curzibn/Luban#242]
之前依赖的 1.1.3 版本，现在打开项目突然提示找不到 Luban 类文件了。

**Comment by Curzibn** [comment]
你好，1.1.3在jcenter上并没有改动过，你看看是不是其他原因造成的。而且我这边新项目测试导入没问题。

**Comment by lvfaqiang** [comment]
谢谢~，我这边重新依赖一下又可以了。不好意思，打扰了。
