### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/media/ExifInterface;

### ISSUE THREAD

**Issue by gyb3320** [Curzibn/Luban#248]

**Comment by T-mans** [comment]
我是从1.1.3升级到1.1.5之后，遇到这个问题的

**Comment by T-mans** [comment]
我是从1.1.3升级到1.1.5之后，遇到这个问题的
后来我在项目添加了依赖：
implementation "com.android.support:exifinterface:27.1.1"
解决了这个问题

**Comment by yangfengfeng** [comment]
我加了这句话，但是这句话在gradle中直接爆红，而且这个错误依旧还在
