### ISSUE TITLE
Engine文件下ExifInterface找不到

### ISSUE THREAD

**Issue by hanxiaoqiangfly** [Curzibn/Luban#249]
现在应该用import android.media.ExifInterface;

import android.support.media.ExifInterface;不存在了

**Comment by zaxcler** [comment]
那只能导库自己修改？

**Comment by hanxiaoqiangfly** [comment]
implementation 'top.zibin:Luban:1.1.5'
implementation "com.android.support:exifinterface:27.1.1"
这两个都导入
详细可以看这个https://blog.csdn.net/qq_21434809/article/details/80521772
