### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: quality must be 0..100

### ISSUE THREAD

**Issue by tyousyuka** [Curzibn/Luban#25]
红米Note 2 上一张8.05M的图片出现这个错误，小点得图片没事，求指导

**Comment by Curzibn** [comment]
最近有点慢，只能抽空一点点做

**Comment by TangXiaoLv** [comment]
@tyousyuka 我的做法是在测量options 的while 循环内加了if(opthins <= 0)判断，如果小于，就强制给opthins设置一个值并退出循环。 不过说回来，这里循环压缩比较耗性能，时间。作者能不能优化下？

**Comment by mackkill** [comment]
这种循环测量options 当遇到比较大的图片的时候会出现负数的情况，我之前也遇到过。虽然当到一定值后判断跳出，但是会发现图片压缩的效果不怎么好。最后我的解决方案是先按屏幕尺寸缩放到合适分辨率，在检测图片的大小进行设置压缩值：大于1m的压缩40%， 500k到1m的压缩60%， 以下的就80%。可以根据自己的业务需求来。希望对你有帮助。

**Comment by Curzibn** [comment]
@tyousyuka 可以提供下图片的分辨率吗？

**Comment by tyousyuka** [comment]
@Curzibn 2368 × 4208

**Comment by Curzibn** [comment]
这条 issues 已修复
