### ISSUE TITLE
压缩之后,如何保存jpeg的位置信息?

### ISSUE THREAD

**Issue by WuZhaogang** [Curzibn/Luban#256]
项目需求,在压缩后,要获取到拍摄地点,请教一下,这个该怎么处理

**Comment by Curzibn** [comment]
你需要在压缩前取出原图的拍摄位置存储，再在压缩后将存储的位置信息写回压缩完的图片里。
`Android`操作`jpeg`图片信息可参考https://developer.android.com/reference/android/media/ExifInterface
