### ISSUE TITLE
压缩没有图片后缀名的图片

### ISSUE THREAD

**Issue by Yuphee** [Curzibn/Luban#258]
压缩一些是图片但是经过加密没有后缀名（比如QQ保存得图片）然后去压缩这类文件就会报StringIndexOutOfBoundsException

**Comment by Curzibn** [comment]
请使用1.1.6的看看，目前的demo使用的都是无后缀图片测试的

**Comment by Yuphee** [comment]
我是用1.1.6，然后是rxjava那种同步得方式
