### ISSUE TITLE
可以统一设置压缩后生成的格式吗

### ISSUE THREAD

**Issue by protectedMan** [Curzibn/Luban#265]
webp的图想压缩成jpg

**Comment by Curzibn** [comment]
压缩是如果没设置保留`alpha`透明通道最终都会以`jpeg`模式保存，你的情况只需要调用重命名方法把压缩后图片后缀指定为`jpg`就行

**Comment by protectedMan** [comment]
因为我会有webp格式的图片，压缩后保存为jpg或者png以兼容iOS。
这不是改后缀名可以解决的事。

**Comment by Curzibn** [comment]
就算`webp`格式只要进了压缩最后出图都是`jpeg`格式，压缩过是不会以`webp`格式存储的
我源码中已经指定压缩结果格式为`Bitmap.CompressFormat.JPEG`了
```tagBitmap.compress(focusAlpha ? Bitmap.CompressFormat.PNG : Bitmap.CompressFormat.JPEG, 60, stream);```

**Comment by protectedMan** [comment]
好的，可能是设置最小压缩大小把webp给忽略掉了，没有经过压缩转码就传到了服务器。
