### ISSUE TITLE
8.0的路径访问权限兼容问题

### ISSUE THREAD

**Issue by chy116449859** [Curzibn/Luban#268]
如果系统是8.0的，crop时用FileProvider获取的路径访问时需要权限，这个得做兼容。如果不crop就不涉及权限的问题，请楼主解决问题后顺便解答一下是为何，让大家学习学习。

**Comment by Curzibn** [comment]
7.0之后的权限系统有很大更新，这块需要开发者自己去学习，而且网上也有很大教程。
luban只做图片的压缩，读写权限需要在你自己的主项目里做处理
