### ISSUE TITLE
Engine.compress(Engine.java:79) this line throws java.lang.NullPointerException,please fixed.thx

### ISSUE THREAD

**Issue by steven-gao** [Curzibn/Luban#270]
日志如下：

Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference

top.zibin.luban.Engine.compress(Engine.java:79)

**Comment by steven-gao** [comment]
thank you

**Comment by steven-gao** [comment]
i review the code, i think this block code still have a nullpointer exception ,maybe i am wrong:

File compress() throws IOException {
    BitmapFactory.Options options = new BitmapFactory.Options();
    options.inSampleSize = computeSize();

    Bitmap tagBitmap = BitmapFactory.decodeStream(srcImg.open(), null, options);
    ByteArrayOutputStream stream = new ByteArrayOutputStream();

    if (Checker.SINGLE.isJPG(srcImg.open())) {
      tagBitmap = rotatingImage(tagBitmap, Checker.SINGLE.getOrientation(srcImg.open()));
    }
/////////// this tagBitmap doesn't judge null before used.
    tagBitmap.compress(focusAlpha ? Bitmap.CompressFormat.PNG : Bitmap.CompressFormat.JPEG, 60, stream);

**Comment by GlimmerYang** [comment]
请问下～这个问题解决了吗～现在我这边检测到多种机型都报错这个错～自己无法重现
