### ISSUE TITLE
红米3s Android 6.0 压缩返回还是源路径，没有进行压缩

### ISSUE THREAD

**Issue by zhyazaq** [Curzibn/Luban#285]
公司大部分机型压缩的返回的路径都是默认的luban_cache路径，但是红米3s遇到的是原路径。在压缩保存的路径找不到，不管指不指定压缩路径，结果都是手机原路径。

**Comment by Curzibn** [comment]
能否用源码调试下，手头上没有红米3s的手机

**Comment by zhyazaq** [comment]
![m4muce x5 ahms2t7 i65j](https://user-images.githubusercontent.com/17999923/44184247-0003df00-a141-11e8-92d0-47f42957cb80.png)

**Comment by zhyazaq** [comment]
上面两个listener都是null

**Comment by Curzibn** [comment]
Luban库的默认压缩存储文件夹是在缓存文件里，所以不需要设置sd请求权限。example出于方便也未做sd权限设置。现在开发app一般都要动态获取sd卡读写权限才能在sd卡里生成文件夹。
