### ISSUE TITLE
android低版本（4.3）出现 Orientation not found 高版本正常

### ISSUE THREAD

**Issue by JohnsonJLi** [Curzibn/Luban#286]
求大神指点 
http/1.1 (180844-byte body)
不压缩有点难受

**Comment by Curzibn** [comment]
能否描述清晰点，低版本是指系统版本还是luban版本

**Comment by JohnsonJLi** [comment]
不好意思  
implementation 'top.zibin:Luban:1.1.7'
android 系统版本 4.3
比较老的机型  
要给老机型做适配发现了这个问题
图片在手机里是存在的

**Comment by kevinwork** [comment]
android 5.1也发现这个问题

**Comment by caocao123** [comment]
implementation 'top.zibin:Luban:1.1.8' 
android 7.1.2 也有这样的问题

**Comment by dyf505776897** [comment]
implementation 'top.zibin:Luban:1.1.8'
android 5.1 也有这样的问题

**Comment by 982244278** [comment]
andriod 8.1 也出现这样的问题

**Comment by xiaoshubin** [comment]
implementation 'top.zibin:Luban:1.1.8'
andriod 10 也出现这样的问题

**Comment by CMzhizhe** [comment]
邮箱已经收到
