### ISSUE TITLE
Rxjava线程错误

### ISSUE THREAD

**Issue by TZ-TimZhang** [Curzibn/Luban#30]
`Luban.get(activity).load(file).putGear(Luban.THIRD_GEAR).asObservable().subscribeOn(Schedulers.io()).observeOn(AndroidSchedulers.mainThread())`
运行压缩后界面会卡主，主线程被阻塞。subscribeOn方法好像无效

**Comment by 2tu** [comment]
@TZ-TimZhang 
asObservable()方法中
Observable.just(thirdCompress(mFile.getAbsolutePath()))修改为
return Observable.just(mFile.getAbsolutePath()).map(new Func1<String, File>() {
        @Override public File call(String path) {
          return thirdCompress(path);
        }
      });

first同理

**Comment by Curzibn** [comment]
@2tu 感谢你的提示，已经修复阻塞问题。
