### ISSUE TITLE
关于多图压缩内存问题

### ISSUE THREAD

**Issue by pinkApple** [Curzibn/Luban#34]
看到最新支持了多文件的压缩处理..
那么,当同时进行8个图片的压缩的时候,
势必会出现8个bitmap在内存..8个bitmap同时在进行循环压缩到指定大小...
那么, 很容易就会出现out of memory.
有没有一种方式.扔出8张图片, 以队列的形式每次压缩2张左右.分4次压缩完成.

**Comment by Curzibn** [comment]
多文件处理目前还没完成，还未决定采用何种形式处理

**Comment by pinkApple** [comment]
rxjava我试了,感觉不好处理这种逻辑.找不到如何实现这种队列...
用线程池实现比较快吧.

**Comment by pinkApple** [comment]
通过设置 android  largeHeap = true解决了内存溢出问题.. 
该问题Close.

**Comment by gushoubang** [comment]
感觉设置 android largeHeap = true，解决内存溢出问题不太好

**Comment by pinkApple** [comment]
这里的内存是正常的,非泄露的..用内存空间换时间.用完就会自动回收释放掉.
