### ISSUE TITLE
0.5625、1664等数值的意义

### ISSUE THREAD

**Issue by fengqingxiuyi** [Curzibn/Luban#38]
thirdCompress方法中
if (scale <= 1 && scale > 0.5625) {
            if (height < 1664) {
                size = (width * height) / Math.pow(1664, 2) * 150;
                size = size < 60 ? 60 : size;
           ...
        }
为什么要用0.5625、1664等数值进行判断？

**Comment by Curzibn** [comment]
[查看这里](https://github.com/Curzibn/Luban/blob/master/DESCRIPTION.md)

**Comment by fengqingxiuyi** [comment]
看了，不懂你是怎么得到这些数据的，是通过微信逆推的么？，比如这个：
[1, 0.5625) 边界值为：1664 * n（n=1）, 4990 * n（n=2）, 1280 * pow(2, n-1)（n≥3）
怎么得到1664、4990这些?

**Comment by Curzibn** [comment]
就是微信逆推

**Comment by fengqingxiuyi** [comment]
好吧
