### ISSUE TITLE
java.lang.ArithmeticException: divide by zero

### ISSUE THREAD

**Issue by TangXiaoLv** [Curzibn/Luban#4]
thirdCompress

`else if (c <= 0.5625 && c > 0.5) {
            int multiple = j / 1280;
            k = i / multiple;
            l = j / multiple;
            s = (k * l) / (1440.0 * 2560.0) * 200;
            s = s < 100 ? 100 : s;`
multiple有可能为 0

**Comment by aohanyao** [comment]
在华为P9上面出现这个这个问题，如何解决？
