### ISSUE TITLE
这么多star我搞不懂啊

### ISSUE THREAD

**Issue by yhb612** [Curzibn/Luban#41]
return BitmapFactory.decodeFile(imagePath, options);

归根结底就这一句话而已

**Comment by xxxifan** [comment]
算法比较重要吧

**Comment by NashLegend** [comment]
唉，太水了

**Comment by liupeng110** [comment]
小菜比太多了....

**Comment by xxxifan** [comment]
尴尬，butterknife归根结底还是setOnClickListener呢
被邮件炸进来，看了下这个库的issues简直惨不忍睹，就不能尊重一下别人的成果？

**Comment by liupeng110** [comment]
主要是楼主太浮夸,最像微信的压缩工具  噱头太大
跟微信比较  你从多方面比较,清晰度完全没提
技术含量太低了  不自重,别人怎么尊重他

**Comment by Zhangxxl** [comment]
最起码人家愿意分享, 而且代码是公开的, 你可以用也可以不用, 何必这么说呢, 觉得没什么用就自己实现呗, 让作者看了情何以堪

**Comment by liupeng110** [comment]
而并且耦合度 还大   rx系列  ....

**Comment by liupeng110** [comment]
Universal-Image-Loader，android-Volley，Picasso、Fresco和Glide

**Comment by liupeng110** [comment]
楼主的方法就是很古老的调用系统api  自适应压缩,现在他还给弄得更耦合了

**Comment by liupeng110** [comment]
如果核心功能写成一个util类,我想没那么多人喷了

**Comment by liupeng110** [comment]
另外,我没用butterknife ,因为oncreat里还要再插一句,你用过xutils么

**Comment by xxxifan** [comment]
我用rx，用于图片上传请求写的很方便。
你觉得耦合大，那你可以pull request帮助改进，或者自己写一个算法牛逼的库开源出来

---
原来用了rx还成了被喷的原因了

**Comment by liupeng110** [comment]
rx思想很好,但是被你们用成了屎

**Comment by liupeng110** [comment]
为什么不用rx  
http://www.cnblogs.com/andlp/p/6233201.html

**Comment by liupeng110** [comment]
不单单是rx,本来应该很精简的东西 被楼主写臃肿了

**Comment by Zhangxxl** [comment]
@liupeng110 
我看了一下他的gradle,只依赖了 rxJava和rxAndroid,
```gradle
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.1.1'

    compile 'io.reactivex:rxjava:1.1.6'
    compile 'io.reactivex:rxandroid:1.1.0'
}
```
这两个库应该不少人项目里会用到, 加一块大小应该不超过300K, 当然只有一个地方用到rxJava,去掉更好, 但是你们这样说真的好吗?觉得用RX不好,可以提Issues啊, 总不能上来就打击人

**Comment by liupeng110** [comment]
这两个库应该不少人项目里会用到, 
你用不代表别人都用,
加一块大小应该不超过300K,
如果多了呢,积少成多  一样的道理
当然只有一个地方用到rxJava,去掉更好, 
无可非议
但是你们这样说真的好吗?
直接攻击确实不对,库也真不敢恭维
觉得用RX不好,可以提Issues啊, 总不能上来就打击人
同上

**Comment by xxxifan** [comment]
> 为什么不用rx
http://www.cnblogs.com/andlp/p/6233201.html

这个文章写的  用rx的目的是什么都没搞清楚，还耦合

**Comment by liupeng110** [comment]
要搞清的是写程序的目的,其他都是途径  
很明显rx有点绕远

**Comment by liupeng110** [comment]
文章哪点不对 指出来,一起学习  正愁没人给我指点

**Comment by Curzibn** [comment]
首先感谢 @Zhangxxl @xxxifan ，非常非常感谢你们。
本来这么多star其实我也没料到， @yhb612 提出来我确实没法回答。

但是 @liupeng110 您说“小菜比太多了....”这点我不能同意。所以我回去翻了star列表，star这个项目的人有就职于NetEase、Baidu、Xiaomi、HP、PPTV、YY、Didi、携程、Tencent、糗事百科、Qihoo 360、Kuaidi、Meitu、Meizu、tmall.com、Alibaba、ele.me、SOHU、北京58同城等等这些公司的人（以Github用户自行填写的Company资料为数据）。你一句小菜比就把他们概况起来，那我想请问您就职于什么公司，拥有什么成就来评价这些人！

@liupeng110 您说我不自重，怎么说我都好，我也不在乎，但是您非要在这里显示您的存在感确实对关注这个项目的人产生了不好的影响。希望您能自重！

我想过你们为什么会对着我的项目开喷，以下是我的一些猜想，对或不对您可以提出来：
1）我的项目的存在对您的利益造成不良影响甚至是伤害？例如，您用了之后出问题了，导致您的薪资，奖金什么的受到影响。这点我想无可厚非，毕竟这是开源项目，我也用过别的开源项目出问题的。您回来如果提出问题就行，何必冷嘲热讽。
2）您觉得我通过欺骗你们博取眼球，赚取star？首先，我这项目开源出来的时候并没有做过任何的推广，简书上写了文章结果没上推荐估计没什么看的，开发者头条写了文章结果也没上每日头条估计还是没什么人看到。直到突然有个大大推荐了一下（这里我不想说哪个，省得他们去喷那个大大没眼光）才突然star多起来。然后呢，这个issues从2016年8月提出来开始就不断有人质疑，那时候才1000+star，但是你们的质疑依然无法阻止我star的提升，难道这也是我的错？
3）您觉得我通过这个项目取得很多特殊的待遇？我只想说我是刚刚面试完来写这条评论的，开源这个项目后我的职业生涯并没有什么变化，16年下半年依然动荡，找到的公司受市场影响解散的也有，休业拖欠工资的也有，或许您的生活才是我向往的呢。

最后是一点解释，这项目之所以这么长时间没有维护第一是去年下半年生活一直动荡不安，工作的，家人的各种问题；第二是确实很多issues像长图的问题很棘手。当然只有还有人star着我就不会放弃维护。

就这样吧，下午还要去面试呢！

**Comment by liupeng110** [comment]
作者居然到了
1.首先要感谢大家,无论片面全面观点都是有助于开源的
2.是我的概括. 我从没问你在什么公司就职,拥有什么水平.凡事看代码,不是论资排辈 
 我感觉概括这3.7k    "小菜比太多了"   也算比较符合实际    
3.因为一开始你这个github上对这个库介绍写的 最接近微信压缩算法(ps现在已经改了仿微信这很正常) 

你想的太多
+1.我没在项目中用你写的库,自己玩也没用你的   
+2.一开始是那样觉得,后来已经无所谓了   我没用rx正好也交流下  了解了解现在的情况
+3.我希望你能有些好的待遇,开源的本质是很好的     
 
.不用想了  我是因为感到奇怪你这样写  才喷的  
因为在我看来
你的核心 xxxCompress   那些(压缩,图片自适应大小)完全可以写在一个工具类里 
跨平台,使用简单    .另外turbo这个库是从c层进行压缩 可以看看      
最后 新年快乐!

**Comment by ZQiang94** [comment]
一直关注这个项目，有issues动态我邮箱也会提示，心情好好的怎么看到作者发了长文，看了上下文才知道作者为何发那么长的issues，我只是把自己的想法写出来，不服气的可以来喷！
首先对作者开源和长期维护的精神点赞，我自己也是尊敬每一个开源er。其次喷子们你看看你们自己有啥拿得出手的开源项目，还好意思来这喷？要有**自知之明**好不好！
自己没有做好之前就不要喷一个比你努力还比你牛逼的人！或事！
做不到为开源社区做贡献不要紧，但请不要扰乱，这是关乎**道德的**。
--------更新-----
我说的只是喷子，请对号入座。

**Comment by liupeng110** [comment]
有什么说什么而已,哪个项目都有可优化的地方  
别人指出来可以一起交流                                                                     
1.被别人激怒,说明你自己修养不够
2.评论个电冰箱还要比电冰箱更会制冷?
3.从清晰度 压缩质量 来说 跟微信的确实   
不在一个层次,

**Comment by wsf5918** [comment]
@liupeng110 还是不会讲话啊，回去学学先。你搞个牛逼的出来，来，亮瞎我们的眼睛。

------------最讨厌这种，看了别人的东西，然后，又这种嫌弃的，并非说不得，而是方式不对。拿出来分析啊，哪个地方可以改进啊，U Can U Up。

**Comment by liupeng110** [comment]
翻上去看看,已经说过了
1.引入rx系列,单独的工具类最好不要引入第三方的一些类库  更不要说rx还有很大争议性
2.核心功能完全可以精简为一个类  跨平台,可移植  方便使用(这样做喷的不会那么多)
3.清晰度的调整. luban库只是用了sdk里的api,很早以前就已经这样搞了.
并没有实质性解决失真问题.只对size压缩 (这才是核心问题)

Universal-Image-Loader，android-Volley，Picasso、Fresco和Glide
哪个都够你学了,
关于图片清晰度处理,你们用过turbo这个库么,看看别人的处理思路


@wsf5918     开源就是集思广益,有则改之无则加勉.

-----------最看不起这种没见过市面的小菜比.容不得一点其他意见

**Comment by jacklydoudou** [comment]
@liupeng110 说实话,大家都没错,不过你就是嘴欠

**Comment by liupeng110** [comment]
我对代码有洁癖

**Comment by yizuochengchi** [comment]
好了 作者能开源的精神已经很难能可贵了 可能写的不是太完美 但是比某些公司用开源的 还不遵守开源协议强的多吧？ 你觉得作者什么地方写的不好 你可以指出来 并提出优化方案 大家一起学习嘛 ！ 不要一上来就喷！ 作者加油~！  别受其他人影响~

**Comment by liupeng110** [comment]
在as没有流行eclipse盛行时候压缩图片就是用这种方法
现在还用说明你真out了
水的一比

**Comment by iielse** [comment]
@liupeng110 BB这么多干嘛。楼主开源已是不错。你有代码洁癖此项目又对你要帮助， 要么pull，要么自己copy核心呗。

**Comment by liupeng110** [comment]
@iielse  我没用这个  何来pull和copy   
另外这个方法就是很早以前 最原始的压缩方法    你现在还在用？

**Comment by iielse** [comment]
@liupeng110 先聊一下'技术程序代码'方面的处理风格，说实话我和你相似，喜欢纯净的感觉，butterknife我开始在用，后来也不用了，甚至Fragment我在一年前就没再用了(doge)。这是我忍不住艾特你的原因。。 我和你看法差不多，但是你的人品似乎还是不够，说话太炸了，别人又没有惹你，分享出一个项目是需要耗费作者大量时间和精力的，如果你有过类似的贡献应该是不会这样说话的。这是我忍不住跳出来艾特你的原因。

你说的“我没用这个”，那请问你用的是啥，给个链接看看。
场外聊完了，说场内。

楼主强行集成在这个库rx确实是有点不合适，一大部分的issue和rx有关意见说明了问题。
可以尝试拆成2个，1分为2，类似
`compile 'com.squareup.retrofit2:retrofit:2.1.0'`
`compile 'com.squareup.retrofit2:adapter-rxjava:2.1.0'`
因此
`compile 'top.zibin:Luban:1.0.9'`
`compile 'top.zibin:Luban-rxjava:1.0.9'`

`Luban.java`  核心暴露压缩图片方法
`public static Bitmap compress(Bitmap srouce, int width, int height, int angle, long size)` 
rx部分新建类 `RxLuban.java` 什么的

这样用rx和不用rx的都皆大欢喜了。

看了issue列表后，作者的算法似乎还是有一些小问题，对 #121  #99  #86  #80 #11 #52 这样的情况。。可惜我也是个彩笔，帮不到作者。 还在观望，坐等更新解决  。

**Comment by liupeng110** [comment]
@iielse  
0.看来咱们编程风格差不多，你常用哪些东西？分享分享
1.炸   一是为了多跟有想法的人交流，二是因为这个项目的标题  可能是最接近微信朋友圈的图片压缩算法
---不注重压缩质量,完全没有可以相提并论的地方，在我看来是哗众取宠  我觉得说话太炸的不是我  
2.不用butterknife你用的什么 能说下么 我用xutils3
3.我感觉fragment还可以 ，不用你只用activity么有些场景太重量级了吧？  较多页面替换的场景你怎么处理的  比如购物车 等
4.我用 imageloader 和libjpeg-turbo啊
foke的安卓工程  https://github.com/liupeng110/libjpeg-turbo
Bitmap loadImageSync =  ImageLoader.getInstance().loadImageSync(img_url); //appclication中需配置参数
//这是同步代码，一般我会在外面套一层异步任务
5.rx思想是好的但是被大部分人用成了屎 一个逻辑用很多个异步非常2 。抛开rx 不谈,这只是一个图片压缩类，完全可以只保留一个类。对外暴露方法/接口 
6.

**Comment by ImKarl** [comment]
@liupeng110   哥们，工作几年了？在哪高就啊？

ps：仔细看了你的评论。提两个想法：
1、imageloader 是指 Android-Universal-Image-Loader 吗？
作者提到从11月27日起停止维护   UIL [27.11.2011 - 27.11.2015]
2、“rx 被大部分人用成了屎 一个逻辑用很多个异步非常2 ”
你分享的博文我去评论了，见 [#4楼](http://www.cnblogs.com/andlp/p/6233201.html#3715310)

**Comment by dingbuoyi** [comment]
我觉得该项目的核心 应该是 Engine里的 computeSize 方法，还是挺有参考价值的，谢谢作者

**Comment by dingbuoyi** [comment]
@liupeng110 我提个小建议啊

  private Bitmap.CompressFormat getFormat(Bitmap bitmap) {
if (bitmap.hasAlpha()) {
      return Bitmap.CompressFormat.PNG;
    } else {
      return Bitmap.CompressFormat.JPEG;
    }
  }

加个判断会比写死的好
