### ISSUE TITLE
压缩后图片色彩出现失真现象

### ISSUE THREAD

**Issue by airtayork** [Curzibn/Luban#43]
红米1s拍的照片，压缩之后部分照片会出现比较严重的颜色失真

**Comment by 2tu** [comment]
@airtayork 把原始照片发上来，大家分析分析呗

**Comment by airtayork** [comment]
比如这张照片，

![img_20151122_151126](https://cloud.githubusercontent.com/assets/2181245/17687424/62e8fe36-63a7-11e6-839b-b5d947a1a50c.jpg)

**Comment by bbqichang** [comment]
![36308776151916461](https://cloud.githubusercontent.com/assets/13122266/17689188/5d1a6f9c-63b8-11e6-9cea-33ae352c0740.jpg)
这张图片也会失真

**Comment by airtayork** [comment]
我发的仅仅是其中一张，大部分图片处理之后都会显示质量差很多。

**Comment by bbqichang** [comment]
@airtayork 你把这里的数值调大一点 ，压缩完之后图片的尺寸会稍大一点  失真就不明显了
![sss](https://cloud.githubusercontent.com/assets/13122266/17690496/8fc2b6ee-63c1-11e6-9b8a-4168b01eabcf.png)

**Comment by 2tu** [comment]
的确是失真了，这个和图片的像素有关，缩小后色彩更浓了
但是苹果系统自带的预览修改图片大小，修改后图片未出现这种情况，里面有一个重新采集的选项，不知道对应是如何实现的

@bbqichang 修改大小只是针对已知图片参数或者可以接受图片大一点的情况下，如果业务上都可以确定图片大小可以直接修改。

**Comment by airtayork** [comment]
@bbqichang 不改的情况下压完都有497k呢，有点大了

**Comment by airtayork** [comment]
不好意思，前面看错了，不改的情况下压完也就100多k。后来我把质量提高了一些，就可以了。

**Comment by bbqichang** [comment]
https://github.com/zetbaitsu/Compressor

**Comment by wjyin** [comment]
我也是遇到这样的问题，原因是图片质量参数过低，而图片的宽高压缩得也不够。我试过你上面的那张带湖的图，最后得到的质量只为4，我也只能把图片质量提高来解决问题了

**Comment by 2tu** [comment]
这个公式应该主要用于最大可能还原微信的基本压缩率。但是具体的还得按照自己的业务来。
微信有一个查看原图的功能，也是为了压缩后不清晰，可以直接下载原图。

1、压缩比针对业务处理
2、优化压缩算法(https://github.com/2tu/bither-android-lib)

**Comment by gushoubang** [comment]
https://tinypng.com/
https://github.com/pornel/pngquant
