### ISSUE TITLE
必须要依赖RxJava？

### ISSUE THREAD

**Issue by linzhengloser** [Curzibn/Luban#44]
希望能改一下这个地方

**Comment by starry001** [comment]
可以把代码拷出来自己修订制改，我就这么做的

**Comment by MIkeeJY** [comment]
RxJava是优化了线程阻塞的问题么？？？

**Comment by Curzibn** [comment]
目前来说是的

**Comment by MIkeeJY** [comment]
@Curzibn 我对比了您之前的代码 发现算法神马的都没变化 但是我项目里不想依赖rxJava，那个包包含了5000多个方法。。希望您同时也搞个不一定必须依赖rxJava的。。

**Comment by KitTak** [comment]
如果不想依赖RxJava，可以单独拆分出来使用

**Comment by qstumn** [comment]
对RxJava不怎么一窍不通的表示不知道怎么把RxJava拆出来.....

**Comment by MIkeeJY** [comment]
@qstumn https://github.com/shaohui10086/AdvancedLuban 推荐用这个
