### ISSUE TITLE
是否可以控制不压缩

### ISSUE THREAD

**Issue by nyjsl** [Curzibn/Luban#5]
当图片本身大小很小的时候会出现压缩后图片变大的结果

**Comment by Curzibn** [comment]
麻烦请提供下图片信息，方便我还原情景调试

**Comment by nyjsl** [comment]
你好,详细信息以通过369443889@qq.com邮箱发送到你270206244@qq.com的邮箱中了,请查收

**Comment by Curzibn** [comment]
@nyjsl 收到，谢谢你的反馈

**Comment by Curzibn** [comment]
已经修复
