### ISSUE TITLE
常用尺寸和微信压缩比不一致

### ISSUE THREAD

**Issue by YangHanqing** [Curzibn/Luban#57]
采用的方式是，从相册选择图片发送朋友圈，等待一时，压缩完成后，保存到相册。
我上传了一张1300w-4:3的图片，luban 是长宽各压缩1/2,微信是的1280*960。
又测试了一张1080P 的截图，luban 尺寸保持1080P，微信是的720P。
因为图片尺寸大了很多，所以在同等大小的情况下，luban 的画质损耗程度完全不可接受。
不知道为什么和作者的测试数据差那么多，是我的测试方法和作者不一致吗？

**Comment by xwpeng** [comment]
从源码看是计算图片的压缩条件，最终还是系统的压缩方法．这样一些图片就会出现严重失真，比如png横图．到底还是无法细微控制压缩力度．同一张图微信不失真，这个失真．
