### ISSUE TITLE
压缩后文件的后缀名没了

### ISSUE THREAD

**Issue by xmjharry** [Curzibn/Luban#62]
压缩后文件的后缀名没了

**Comment by gushoubang** [comment]
看这里https://github.com/Curzibn/Luban/issues/13

**Comment by xmjharry** [comment]
谢谢。由于服务端会根据图片后缀名做不同的压缩方式，采用指定压缩后图片存储路径得以解决。

**Comment by Curzibn** [comment]
1.1.2 版本后都会有后缀
