### ISSUE TITLE
压缩后分辨率变得非常小

### ISSUE THREAD

**Issue by zeyu163** [Curzibn/Luban#68]
原本2560_1440的图片压缩完就变成了640_360了，这样太小了。请问可以设置期望的尺寸吗？比如1280*720之类的。

**Comment by zeyu163** [comment]
原本2560x1440分辨率的图片压缩完就变成了640x360了，这样太小了，请问可以设置一个期望的尺寸吗？比如1280x720之类。

**Comment by w0080626** [comment]
同问 +1

**Comment by Curzibn** [comment]
如果是已经有目标比例的话完全不需要用到Luban，直接调用系统的函数设定尺寸进行压缩就可以。Luban的压缩依然采用系统函数压缩，只是设定一系列的压缩规则

**Comment by w0080626** [comment]
@Curzibn  是这样的，拍照压缩是没有问题的，截图压缩的话 或者从网上下载的图压缩的话会非常模糊 而且分辨率非常低。
