### ISSUE TITLE
Luban  压缩后得到的文件路径问题

### ISSUE THREAD

**Issue by BloodBamboo** [Curzibn/Luban#69]
Luban.get(getContext())
                            .load(new File(item.path))                     //传人要压缩的图片
                            .putGear(Luban.THIRD_GEAR)      //设定压缩档次，默认三挡
                            .setFilename(SDCardUtils.SdPath(getContext(), "qa") + System.currentTimeMillis() + "." + FileUtils.getFilenameExtension(item.path))

为了在压缩后有时是没有后缀,所以设置文件路径名称,使其压缩后按该文件路径跟名称保存.
但是,目前情况是得到的文件结果不可预料...有时候是按设置的路径名称,有时候是原路径,设置的没有起作用.对于该方法到底是起到一个什么作用疑惑.我就是想压缩后按我给的路径生成文件,希望能给出具体的解决方案.

**Comment by ycpbyht** [comment]
前面重命名下这个地址
public static String DEFAULT_DISK_CACHE_DIR = "yourname";

然后在你选择压缩的档位处，比如我是第三档

    private File thirdCompress(@NonNull File file) {
        String thumb = mCacheDir.getAbsolutePath() + "/" + randomString(8) + ".jpg";

        double size;
        String filePath = file.getAbsolutePath();
然后就好了

**Comment by yx19861211** [comment]
我设置
Luban.DEFAULT_DISK_CACHE_DIR = SDCardUtils.SdPath(getContext(), "qa") + System.currentTimeMillis() + "." + FileUtils.getFilenameExtension(item.path);
:这是设置的具体值  /storage/emulated/0/edu_edu_i/qa_download/1475919783149.jpg

最后得到的文件路径是下面:
/data/data/cn.com.edu_edu.i/cache/storage/emulated/0/edu_edu_i/qa_download/1475919702044.jpg/1475919702212

该方法并不是我希望得到的结果.我是想让压缩后返回我设置好的路径跟文件名.不是在原基础上加了前缀跟后缀....

**Comment by yx19861211** [comment]
返回原路径好像是,因为图片本身不大,不用压缩就会返回原路径,如果图片大,就会按我最早设置的方法,返回我想要的文件.希望作者能够给出具体的说明.

**Comment by Curzibn** [comment]
@yx19861211 压缩前是有做大小判断的，只要不用压缩就会直接返回原文件以节约资源。

**Comment by yx19861211** [comment]
@Curzibn 作者的意思是,就是使用setFilename来设置你想要的路径跟文件名称,但是如果图片本身就不大就会跳过压缩过程,直接返回源文件,所以你设置的文件路径也就不起作用.
我觉得这个可以增加一些设置,既然设置了文件名跟路径,使用人一般都是希望返回的是你想要的,如果特殊情况,再直接返回,希望下个版本能做相应的修改,或者弄个分支,我去修改,呵呵

**Comment by Curzibn** [comment]
1.1.2 后的版本都有后缀
