### ISSUE TITLE
增加内部多线程处理

### ISSUE THREAD

**Issue by Curzibn** [Curzibn/Luban#7]
新版添加多图片同时处理功能，方法名如下
`public Luban load(List<File> files){
    //TODO compress image list
}`

**Comment by zhangchaoxu** [comment]
looking forward to this new feature.

**Comment by Zzz468005600** [comment]
looking forward too

**Comment by zhangchaoxu** [comment]
针对多文件处理，我尝试写了一个，有不完善的地方，由于修改了回调接口，无法兼容原先的，仅供参考。不确定[PR](https://github.com/zhangchaoxu/Luban/commit/69a7f6e9674c86a441b526e5a586159208718b75)是否提交成功。

**Comment by zhangchaoxu** [comment]
Thanks again for your great job @Curzibn

**Comment by morosek** [comment]
目前版本好像还是不能调用load(List<File> files)方法？

**Comment by zhangchaoxu** [comment]
@morosek  对的，curzibn还没有支持，我试着写了一个，fyr 
https://github.com/zhangchaoxu/Luban/
