### ISSUE TITLE
解决多图压缩OOM的一个建议

### ISSUE THREAD

**Issue by Datartvinci** [Curzibn/Luban#72]
在执行压缩的时候,如果直接新创建线程，那么9张图片的情况下很容易OOM，而单线程虽然不会OOM但是会很慢，所以应该用固定的线程池，具体做法如下：在压缩开始的时候，先getRuntime().gc()回收一下内存，再调用getRuntime().freeMemory()判断可用内存的多少，根据可用内存的数值实例化一个固定的线程池（比如除以5），所有的压缩任务放固定进线程池里面执行，可以配合CountDownLatch来做好线程之间的同步。

**Comment by stronghe123** [comment]
直接调用gc，也不会马上执行回收啊

**Comment by chenlong0525** [comment]
可以详细说明一下吗
