### ISSUE TITLE
压缩后的File没有后缀名,求解哦

### ISSUE THREAD

**Issue by ZengHongHua** [Curzibn/Luban#76]
这是压缩前的路径:/storage/emulated/0/DCIM/GalleryFinal/IMG20161012171724.jpg
压缩后:/data/user/0/com.szcloud8.cloudbulter/cache/luban_disk_cache/1476348826430
获取路劲的方法是 file.getPath();
没有后缀就可能导致显示不出来的,
有什么解决办法吗,用的压缩方式监听的第三档,

**Comment by yx19861211** [comment]
![image](https://cloud.githubusercontent.com/assets/8265300/19544369/00e39894-96b1-11e6-86b3-1b7632c73e54.png)
用setFilename这个方法可以设置名称跟后缀名,但是前提是得压缩,如果判断为不压缩会返回原路径

**Comment by Curzibn** [comment]
1.1.2 后的版本都有后缀
