### ISSUE TITLE
批量压缩有问题

### ISSUE THREAD

**Issue by yuzhiqiang1993** [Curzibn/Luban#79]
```
for (int i = 0; i < activity.selectedImgList.size(); i++) {
        final ImageItem img = activity.selectedImgList.get(i);

        if (img.size / 1024 < 500) {
            /*不压缩  直接添加*/
            compressedImgList.add(new File(img.path));
            checkComplete();
        } else {
            /*压缩后再添加*/
            compressImg(new File(img.path), i);
        }

    }
```

上面是添加压缩任务

然后开始压缩，结果 compressedImgList.add(file);的时候添加的是重复的图片
   private void compressImg(final File imgFile, int position) {
        L.i("压缩图片");
        Luban.get(activity)
                .load(imgFile)
                .putGear(Luban.THIRD_GEAR)
                .setFilename(imgFile.getName())
                .setCompressListener(new OnCompressListener() {
                    @Override
                    public void onStart() {

```
                    Log.i("开始压缩,原图大小：", imgFile.length() / 1024 + "k");
                }

                @Override
                public void onSuccess(File file) {
                    Log.i("压缩完成，压缩后大小：", file.length() / 1024 + "k");
                    compressedImgList.add(file);
                    L.i("添加的文件名是：" + file.getName());

                    checkComplete();

                }

                @Override
                public void onError(Throwable e) {
                    /*压缩失败  添加原图*/
                    L.i("压缩失败  添加原图");
                    compressedImgList.add(imgFile);
                    checkComplete();
                }
            }).launch();
}
```

下面是打印日志

I/压缩完成，压缩后大小：: 191k
10-27 15:02:26.023 28680-28680/com.ship.yzq.ship I/shipApp: 添加的文件名是：IMG_20161027_142337.jpg.jpg
10-27 15:02:26.605 28680-28680/com.ship.yzq.ship I/压缩完成，压缩后大小：: 178k
10-27 15:02:26.606 28680-28680/com.ship.yzq.ship I/shipApp: 添加的文件名是：IMG_20161027_142331.jpg.jpg
10-27 15:02:26.682 28680-28680/com.ship.yzq.ship I/压缩完成，压缩后大小：: 184k
10-27 15:02:26.682 28680-28680/com.ship.yzq.ship I/shipApp: 添加的文件名是：IMG_20161027_142331.jpg.jpg
10-27 15:02:26.781 28680-28680/com.ship.yzq.ship I/压缩完成，压缩后大小：: 189k
10-27 15:02:26.781 28680-28680/com.ship.yzq.ship I/shipApp: 添加的文件名是：IMG_20161027_142327.jpg.jpg
10-27 15:02:26.807 28680-28680/com.ship.yzq.ship I/shipApp: IMG_20161027_142337.jpg.jpg
10-27 15:02:26.807 28680-28680/com.ship.yzq.ship I/shipApp: IMG_20161027_142331.jpg.jpg
10-27 15:02:26.807 28680-28680/com.ship.yzq.ship I/shipApp: IMG_20161027_142331.jpg.jpg
10-27 15:02:26.807 28680-28680/com.ship.yzq.ship I/shipApp: IMG_20161027_142327.jpg.jpg

**Comment by airtayork** [comment]
是的，我也遇到了这样的问题。 @Curzibn 是不是两个压缩任务同时创建了一样的文件名导致的？

**Comment by airtayork** [comment]
看了一下代码，应该就是这个原因，取时间戳作为文件名，如果在for循环里连续添加压缩任务，同一毫秒加入多个任务的几率是很大的。

**Comment by yuzhiqiang1993** [comment]
这就尴尬了，有什么好的解决办法没？

**Comment by airtayork** [comment]
看代码，里面创建文件名的地方判断了有没有设置fileName变量，设置了的话就不会用时间戳了，所以设置一下文件名就可以了。

**Comment by airtayork** [comment]
不对，还有问题，还要注意是单例。。。

**Comment by clm2733227** [comment]
我也遇到这个问题
IMG_20161123_144658.jpg
IMG_20161123_120216.jpg
IMG_20161123_133840.jpg
IMG_20161123_133901.jpg
IMG_20161123_144658.jpg
IMG_20161123_120216.jpg
返回的文件名，1和5，2和6重复了～

**Comment by clm2733227** [comment]
找到了一个新库 Compressor 这个没问题  用rx

**Comment by yuzhiqiang1993** [comment]
Compressor 这个确实没问题，而且压缩速度很快，推荐使用！

**Comment by ImAlipay** [comment]
compressor压缩是异步的吗
