### ISSUE TITLE
有点小问题

### ISSUE THREAD

**Issue by kongnanlive** [Curzibn/Luban#8]
![8bf4dad301b1b341e9ad18d765fa3ab0](https://cloud.githubusercontent.com/assets/2374686/17317029/057b590c-58ac-11e6-953f-92b370fffbad.jpg)
![d40df68dd6f09fcbbb601695a5771d42](https://cloud.githubusercontent.com/assets/2374686/17317046/28ff914a-58ac-11e6-8ae1-caca18a70010.png)

**Comment by Curzibn** [comment]
这个已经有朋友提过了，目前正在解决中

**Comment by kongnanlive** [comment]
好的
