### ISSUE TITLE
请教横版长图压缩的不对

### ISSUE THREAD

**Issue by qstumn** [Curzibn/Luban#81]
竖版长图压缩完挺好的,横版压缩完全不行了

**Comment by qstumn** [comment]
您好，在压缩横向的超长图时，我的一个237763568分辨率的图片被压成1009153，特别的模糊，几乎设么都看不见了，设置成THIRD_GEAR也没什么作用
想请教下怎么解决这个问题

**Comment by xiaolongwuhpu** [comment]
[https://github.com/Curzibn/Luban/issues/86](url)   可以看看我自己优化方案

**Comment by qstumn** [comment]
谢谢
