### ISSUE TITLE
java.lang.NoSuchFieldException

### ISSUE THREAD

**Issue by shenminjie** [Curzibn/Luban#83]
e.e.d.b.an.a(UnsafeAccess.java:109)
3 ......
4 Caused by:
5 java.lang.NoSuchFieldException:producerIndex
6 java.lang.Class.getDeclaredField(Class.java:596)
7 e.e.d.b.an.a(UnsafeAccess.java:106)
8 e.e.d.b.n.<clinit>(MpmcArrayQueue.java:31)
9 e.e.d.j.a(ObjectPool.java:153)
10 e.e.d.j.<init>(ObjectPool.java:57)
11 e.e.d.j.<init>(ObjectPool.java:36)
12 e.e.d.o$1.<init>(RxRingBuffer.java:280)
13 e.e.d.o.<clinit>(RxRingBuffer.java:280)
14 e.d.a(Observable.java:6394)
15 top.zibin.luban.b.a(Luban.java:135)

是什么问题啊？

**Comment by shenminjie** [comment]
Vivo 手机出现的BUG

**Comment by Curzibn** [comment]
@shenminjie 你的项目对Luban进行混淆了，你可以在混淆配置文件里面加上以下代码
`-keep class top.zibin.luban.**{*;}`

**Comment by ironspf** [comment]
有同样的问题，混淆前没问题，混淆后出现的

**Comment by ironspf** [comment]
已经解决了，添加混淆

-dontwarn sun.misc.**
-keepclassmembers class rx.internal.util.unsafe.*ArrayQueue*Field* {
   long producerIndex;
   long consumerIndex;
}
-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueProducerNodeRef {
    rx.internal.util.atomic.LinkedQueueNode producerNode;
}
-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueConsumerNodeRef {
    rx.internal.util.atomic.LinkedQueueNode consumerNode;
}

**Comment by ironspf** [comment]
@shenminjie 
已经解决了，添加混淆

`-dontwarn sun.misc.**
-keepclassmembers class rx.internal.util.unsafe.ArrayQueueField* {
long producerIndex;
long consumerIndex;
}
-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueProducerNodeRef {
rx.internal.util.atomic.LinkedQueueNode producerNode;
}
-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueConsumerNodeRef {
rx.internal.util.atomic.LinkedQueueNode consumerNode;
}`

**Comment by ironspf** [comment]
@shenminjie 
-dontwarn sun.misc.**
-keepclassmembers class rx.internal.util.unsafe.ArrayQueueField* {
long producerIndex;
long consumerIndex;
}
-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueProducerNodeRef {
rx.internal.util.atomic.LinkedQueueNode producerNode;
}
-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueConsumerNodeRef {
rx.internal.util.atomic.LinkedQueueNode consumerNode;
}
