### ISSUE TITLE
Rxjava 依赖

### ISSUE THREAD

**Issue by zymapp** [Curzibn/Luban#88]
是否可以创建一个没有Rxjava依赖的分支出来呢？毕竟不是每个项目都需要用到Rxjava的

**Comment by xiaolongwuhpu** [comment]
说的很在理,希望下次更新1.1版本的时候单独拉一个去掉rxjava,我在项目中是直接去掉了Rxjava/Rxandroid,创建一个异步线程来压缩的,其实不开线程也不没有发生oom,每次最多压缩10张照片,为了防止oom加上一个线程.
