### ISSUE TITLE
微博很长的截图不能压缩

### ISSUE THREAD

**Issue by zlspilgale** [Curzibn/Luban#9]
项目中要上传一张微博长截图，640*11792的尺寸。
 while (stream.toByteArray().length / 1024 > size) {
            Log.d("Luban","quality options："+options);
            stream.reset();
            options -= 6;
            bitmap.compress(Bitmap.CompressFormat.JPEG, options, stream);
  }
此处循环耗时严重，最后报错：参数quality 在0-100范围。
Caused by: java.lang.IllegalArgumentException: quality must be 0..100

**Comment by tyousyuka** [comment]
同样遇到
