### ISSUE TITLE
不支持多张一起压缩？

### ISSUE THREAD

**Issue by xueyaolive** [Curzibn/Luban#92]

**Comment by a1018875550** [comment]
这个很有用，请问是否支持？

**Comment by leonck** [comment]
是啊 一般都是需要多张图片一起压缩的 顺序还不能乱

**Comment by andansky** [comment]
好几个月没动静了啊~~一直在等支持多图压缩的功能。

**Comment by Tobecomebest** [comment]
我是这么写的，用rxjava的操作符处理就行了：
final ArrayList<File> files = ImageUtil.transformPicture(toUpload);

            Observable.from(files)
                    .flatMap(new Func1<File, Observable<File>>() {
                        @Override public Observable<File> call(File file) {
                            return ImageUtil.getCompressObservable(CreateTask.this, file);//这是压缩一张图片的封装方法
                        }
                    })
                    .toList()
                    .subscribeOn(Schedulers.io())
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe(new Subscriber<List<File>>() {
                        @Override public void onCompleted() {
                        }

                        @Override public void onError(Throwable e) {
                            e.printStackTrace();
                        }

                        @Override public void onNext(List<File> files) {
                            //处理最后压缩好的所有图片
                        }
                    });
        }

**Comment by shuaimango** [comment]
同求作者大大早点支持多张异步压缩

**Comment by XConstantine** [comment]
https://github.com/XConstantine/Luban

**Comment by Yanqilong** [comment]
使用Luban的同步压缩结合Rxjava2来实现，代码如下：
/**
         * fileList是List<File>对象
         */
        Flowable.fromIterable(fileList)
                .map(new Function<File, File>() {
                    @Override
                    public File apply(File file) throws Exception {
                        return Luban.with(context).load(file).get();
                    }
                })
                .toList()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Consumer<List<File>>() {

                    @Override
                    public void accept(List<File> fileList) throws Exception {
                       //压缩后的图片路径
                    }
                });

**Comment by Yanqilong** [comment]
使用Luban同步压缩结合Rxjava2来实现多图压缩

``` javascript ```
         /**
         * fileList是List<File>对象
         */
        Flowable.fromIterable(fileList)
                .map(new Function<File, File>() {
                    @Override
                    public File apply(File file) throws Exception {
                        return Luban.with(context).load(file).get();
                    }
                })
                .toList()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Consumer<List<File>>() {

                    @Override
                    public void accept(List<File> fileList) throws Exception {
                    }
                });
``` javascript

**Comment by Yanqilong** [comment]
`我是这样做的，使用Luban同步压缩结合Rxjava2实现多图异步压缩`

```
        /**
         * fileList是List<File>对象
         */
        Flowable.fromIterable(fileList)
                .map(new Function<File, File>() {
                    @Override
                    public File apply(File file) throws Exception {
                        return Luban.with(context).load(file).get();
                    }
                })
                .toList()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Consumer<List<File>>() {

                    @Override
                    public void accept(List<File> fileList) throws Exception {
                         //图片压缩完成得到list
                    }
                });
```

**Comment by RyomaFYx** [comment]
@Tobecomebest  你好，能看看你的ImageUtil.getCompressObservable(CreateTask.this, file); 这个方法吗？rxjava有点不熟，万分感谢！！
