### ISSUE TITLE
好像是导致不清晰的原因

### ISSUE THREAD

**Issue by u787i** [Curzibn/Luban#95]
213, 214 行 width 和 height 转变成了 最短边 和 最长边
```java
        width = thumbW > thumbH ? thumbH : thumbW;
        height = thumbW > thumbH ? thumbW : thumbH;
```

可是后面有用它来当做宽高来计算 (取名字 多么重要)

```java
   thumbW = width / 2;
   thumbH = height / 2;
```

```java
   thumbW = width / 4;
    thumbH = height / 4;
```

是不是想写  ?

```java
thumbW/=2;
```

**Comment by u787i** [comment]
哦 还有和问题 220行 
```java
                if (file.length() / 1024 < 150) return file;
```

最好不要直接返回 file 哦 可以直接拷贝一到目标文件 否则用完压缩图片要删除的逻辑 就把原图删了 ..

一点建议 祝好 ^ , ^

**Comment by shaohui10086** [comment]
关于返回原图的问题，我想探讨一下：

1. 可不可以返回原图？
我个人觉得是可以的，因为官方就有API是这么做的，比如`Bitmap.createScaledBitmap()`这个接口，就是有可能返回原来的`bitmap`

2.压缩完要删除原图的需求
我还没见过这样的需求...真的会有这样的需求吗，如果有，为了这样一个需求去改造工具呢，还是改变工具的使用方式，这个我应该会选择后者。

只是简单说下自己的想法，说的不对的地方，见谅:）

**Comment by u787i** [comment]
如果图片需要压缩 可能是要做上传的 这个时候就需要 清理压缩后的数据了 不是删除原图 而是压缩后的小图

**Comment by u787i** [comment]
Bitmap.createScaledBitmap() 那可是在内存里的对象 而不是文件

**Comment by u787i** [comment]
嘿嘿 其实 这问题 不会有那么大分歧 使用环境不同嘛
