### ISSUE TITLE
多图片压缩，返回的文件可能会一样

### ISSUE THREAD

**Issue by BaiShou** [Curzibn/Luban#98]
项目中经常有多张图片一起压缩，在此间时刻会碰见返回的是同一个文件。

**Comment by BigTimo** [comment]
Luban.get(this)
    .load(File)
   .setFilename(file.getName())

可以解决你这个问题，不过这个setFilename方法他设置过时了


源码中
 private File thirdCompress(@NonNull File file) {
        String thumb = mCacheDir.getAbsolutePath() + File.separator +
                (TextUtils.isEmpty(filename) ? System.currentTimeMillis() : filename) + ".jpg";
由于没有设置finename,默认缓存的文件名是毫秒，for循环的时候，回调的文件路径会重复

new OnCompressListener() { //设置回调

                    @Override
                    public void onStart() {
                        // TODO 压缩开始前调用，可以在方法内启动 loading UI
                    }

                    @Override
                    public void onSuccess(File file) {
                        if(file != null) {
                            Timber.d("压缩成功的图片 %s", file.getAbsolutePath());
                        }
                        listener.success(getBytes(file));

**Comment by AndroidDevo** [comment]
这样也不行啊 @BigTimo

**Comment by XConstantine** [comment]
https://github.com/XConstantine/Luban
不要使用deprecated的setFilename方法
