### ISSUE TITLE
一个图片压缩bug，看2张对比图。

### ISSUE THREAD

**Issue by fantexigod** [Curzibn/Luban#99]
原图：
![50707369013863222](https://cloud.githubusercontent.com/assets/10988632/20917962/89a77aa4-bbcf-11e6-9cd2-1c51a7d0f515.jpg)
压缩图：
![750641903878174179](https://cloud.githubusercontent.com/assets/10988632/20918054/140f8db2-bbd0-11e6-86fb-84c1a4f0f463.jpg)

遇到过么。求解决办法。谢谢

**Comment by fantexigod** [comment]
代码：
 Luban.get(this)
                        .load(new File(tempPath))                     //传人要压缩的图片
                        .putGear(Luban.THIRD_GEAR)      //设定压缩档次，默认三挡
                        .setCompressListener(new OnCompressListener() { //设置回调
                            @Override
                            public void onStart() {
                                // TODO 压缩开始前调用，可以在方法内启动 loading UI
                            }
                            @Override
                            public void onSuccess(File file) {
                                // TODO 压缩成功后调用，返回压缩后的图片文件
                                Log.d("Luban---",file.getAbsolutePath()+file.getPath());
                                uploadImg(file);
                            }

                            @Override
                            public void onError(Throwable e) {
                                // TODO 当压缩过去出现问题时调用
                            }
                        }).launch();    //启动压缩

**Comment by ArtisanM** [comment]
遇到了相同的问题。不过是个别图片会出现这种情况，不是所有图片都有

**Comment by echolong** [comment]
if (height >= 1664 && height < 4990) {
//                thumbW = width / 2;
//                thumbH = height / 2;
//                size = (thumbW * thumbH) / Math.pow(2495, 2) * 300;
//                size = size < 60 ? 60 : size;
                thumbW = (int) Math.floor(width / 3.0f);
                thumbH = (int) Math.floor(height / 3.0f);
                size = (thumbW * thumbH) / Math.pow(1280, 2) * 300;
                size = size < 60 ? 60 : size;
            } 

我这样改了之后，显示比以前正常多了
